services:
  db:
    container_name: taaba_db
    image: mongo:latest
    volumes:
      - db_storage:/var/lib/mongodb/data
    ports:
      - '27017:27017'
volumes:
  db_storage:
    name: db_storage
